# -*- coding: utf-8 -*-
"""Elle düzenlenmiş varlık kataloğu.

Her kayıt: id, ad, takma ad regex'leri, tür, mimari katman, altın küme, yetenek etiketleri.
İçerik alanları (açıklama, lisans, olgunluk vb.) scripts/enrich/*.json dosyalarından birleşir.
"""

GOLDEN = [
    # id, ad, halka, iş tanımı, renk
    ("G01", "Uygulama Kabuğu & Bileşen Temeli", "core", "Sabit, öğrenilebilir kabuk ile erişilebilir temel bileşenleri sağlar.", "indigo"),
    ("G02", "GenUI Sözleşme Omurgası", "core", "Ajan ile arayüz arasındaki olay, tarif ve şema sözleşmelerini tanımlar.", "violet"),
    ("G03", "Renderer & Katalog Motoru", "core", "Tarifi izinli katalog bileşenlerine çevirip ekrana çizer.", "grape"),
    ("G04", "Akış, Taşıma & Dayanıklılık", "core", "Uzun işlerde olayları sıralı, yeniden bağlanabilir ve iptal edilebilir taşır.", "cyan"),
    ("G05", "Durum, Veri & Süreklilik", "core", "Sunucu verisi, ajan yaşam döngüsü ve kullanıcı emeğini ayrı sahiplerde tutar.", "teal"),
    ("G06", "Dosya Alımı & İşleme Hattı", "core", "Seçim → denetim → aktarım → çıkarım → analiz aşamalarını ayırır.", "green"),
    ("G07", "Anlamlı Hareket Sistemi", "core", "Hareketi gerçek durumu anlatmak için, en az araçla ve azaltılabilir kurar.", "pink"),
    ("G08", "AI Etkileşim Bileşenleri", "core", "Onay, araç çağrısı, düşünce zinciri ve akışlı metin için hazır parçalar.", "orange"),
    ("G09", "Analitik Doğruluk & Görselleştirme", "core", "Grafiği dar bir sözleşmeyle, kaynaklı ve doğrulanmış veriyle çizer.", "yellow"),
    ("G10", "Güven, Güvenlik & İzolasyon", "core", "Üretilen tarif ve eylemleri tehdit modeline göre sınırlar ve yalıtır.", "red"),
    ("G11", "Kapsayıcılık, Yerleşim & Token", "core", "Dinamik ekranı erişilebilir, yerelleştirilebilir ve marka içinde tutar.", "lime"),
    ("G12", "Kalite, Test & Gözlemlenebilirlik", "core", "Bozuk akış, performans ve hatayı tekrar üretilebilir biçimde ölçer.", "blue"),
    ("S1", "Kanıt Tabanı & UX Araştırması", "support", "Kararları besleyen deneyler, rehberler ve bekleme çalışmaları.", "gray"),
    ("S2", "Ajan Arka Ucu & Modeller", "support", "Olayları üreten ajan çerçeveleri, sunucular ve dil modelleri.", "dark"),
    ("S3", "Platform, Tarayıcı & Standartlar", "support", "Çalışma zamanı, tarayıcı motorları ve standart kuruluşları.", "gray"),
]

LAYERS = [
    ("L01", "Deneyim & Kanıt", "Kullanıcı deneyi, rehber ve ölçüm dayanakları"),
    ("L02", "Tasarım Dili", "Token, tasarım sistemi ve marka sözlüğü"),
    ("L03", "UI Bileşenleri", "Kit, headless ve AI etkileşim bileşenleri"),
    ("L04", "Hareket", "Animasyon motorları ve tarayıcı hareket yetenekleri"),
    ("L05", "GenUI Renderer", "Tarifi gerçek bileşene çeviren motorlar"),
    ("L06", "GenUI Protokol & Şema", "Olay, tarif ve şema sözleşmeleri"),
    ("L07", "İstemci Durumu & Veri", "Önbellek, durum makinesi, yönlendirme"),
    ("L08", "Taşıma & Akış", "SSE, WebSocket, yama ve satır biçimleri"),
    ("L09", "Dosya Hattı", "Seçim, aktarım ve sürdürülebilir yükleme"),
    ("L10", "Görselleştirme", "Grafik motorları ve grafik dilbilgisi"),
    ("L11", "Kalite & Gözlem", "Test, izleme ve uyumluluk verisi"),
    ("L12", "Güvenlik", "Tehdit modeli, izolasyon ve temizleme"),
    ("L13", "Ajan Arka Ucu", "Ajan çerçeveleri ve sunucu tarafı"),
    ("L14", "Model", "Dil modelleri ve sağlayıcılar"),
    ("L15", "Framework & Runtime", "UI framework'leri, derleyiciler, barındırma"),
    ("L16", "Tarayıcı & Standart", "Tarayıcı motorları ve standart kuruluşları"),
]

# (id, ad, [regex takma adlar], tür, katman, altın küme, [etiketler])
E = [
    # --- G01 Kabuk & temel
    ("mantine", "Mantine", [r"Mantine"], "Kütüphane", "L03", "G01", ["ui-kit", "form", "tablo", "tema"]),
    ("ant-design", "Ant Design", [r"Ant Design(?! X)", r"\bantd\b"], "Kütüphane", "L03", "G01", ["ui-kit", "form", "tablo", "kurumsal"]),
    ("procomponents", "ProComponents", [r"ProComponents"], "Kütüphane", "L03", "G01", ["ui-kit", "form", "tablo", "kurumsal"]),
    ("mui", "MUI", [r"\bMUI\b(?! X)", r"Material UI"], "Kütüphane", "L03", "G01", ["ui-kit", "tema", "form"]),
    ("mui-x", "MUI X", [r"MUI X"], "Kütüphane", "L03", "G01", ["tablo", "grafik", "ticari-katman"]),
    ("heroui", "HeroUI", [r"HeroUI"], "Kütüphane", "L03", "G01", ["ui-kit", "tema"]),
    ("shadcn-ui", "shadcn/ui", [r"shadcn(?:/ui)?"], "Kütüphane", "L03", "G01", ["kaynak-sahipliği", "ui-kit", "tema"]),
    ("daisyui", "daisyUI", [r"daisyUI"], "Kütüphane", "L03", "G01", ["ui-kit", "css", "tema"]),
    ("tailwind", "Tailwind CSS", [r"Tailwind"], "Kütüphane", "L02", "G01", ["css", "tema"]),
    ("react-aria", "React Aria", [r"React Aria"], "Kütüphane", "L03", "G01", ["headless", "erişilebilirlik"]),
    ("radix", "Radix", [r"Radix"], "Kütüphane", "L03", "G01", ["headless", "erişilebilirlik"]),
    ("ark-ui", "Ark UI / Zag", [r"Ark UI", r"\bZag\b"], "Kütüphane", "L03", "G01", ["headless", "çoklu-framework"]),
    ("headless-ui", "Headless UI", [r"Headless UI"], "Kütüphane", "L03", "G01", ["headless"]),
    ("base-ui", "Base UI", [r"Base UI"], "Kütüphane", "L03", "G01", ["headless"]),
    # --- G02 Sözleşme omurgası
    ("a2ui", "A2UI", [r"A2UI(?! React)(?!/)"], "Protokol", "L06", "G02", ["tarif", "bildirimsel", "çoklu-platform"]),
    ("ag-ui", "AG-UI", [r"AG-UI(?! HttpAgent)"], "Protokol", "L06", "G02", ["olay", "akış", "ajan"]),
    ("mcp", "MCP", [r"\bMCP\b(?! Apps)(?!-UI)"], "Protokol", "L06", "G02", ["araç", "ajan"]),
    ("mcp-apps", "MCP Apps", [r"MCP Apps", r"SEP-1865"], "Protokol", "L06", "G02", ["iframe", "tarif", "izolasyon"]),
    ("mcp-ui", "MCP-UI", [r"MCP-UI"], "Protokol", "L06", "G02", ["iframe", "tarif"]),
    ("a2a", "A2A", [r"\bA2A\b"], "Protokol", "L06", "G02", ["ajan", "ajanlar-arası"]),
    ("openui-lang", "OpenUI Lang", [r"OpenUI Lang"], "Format/Şema", "L06", "G02", ["tarif", "dil", "token-tasarrufu"]),
    ("json-schema", "JSON Schema", [r"JSON Schema"], "Standart", "L06", "G02", ["şema", "doğrulama", "form"]),
    ("zod", "Zod", [r"\bZod\b"], "Kütüphane", "L06", "G02", ["şema", "doğrulama"]),
    # --- G03 Renderer & katalog
    ("json-render", "json-render", [r"json-render"], "Framework", "L05", "G03", ["renderer", "katalog", "akış"]),
    ("a2ui-react", "A2UI React Renderer", [r"@a2ui/react", r"A2UI React"], "Kütüphane", "L05", "G03", ["renderer", "react"]),
    ("a2ui-lit", "A2UI Lit / Web Core", [r"@a2ui/web_core", r"@a2ui/web\b", r"A2UI Lit"], "Kütüphane", "L05", "G03", ["renderer", "web-components"]),
    ("copilotkit", "CopilotKit", [r"CopilotKit"], "Framework", "L05", "G03", ["renderer", "ajan", "react"]),
    ("tambo", "Tambo", [r"Tambo"], "Framework", "L05", "G03", ["renderer", "react", "bulut"]),
    ("openui", "OpenUI", [r"OpenUI(?! Lang)"], "Framework", "L05", "G03", ["renderer", "dil"]),
    ("thesys", "Thesys C1", [r"Thesys", r"thesysdev"], "Platform/Servis", "L05", "G03", ["renderer", "bulut", "api"]),
    ("ai-sdk", "Vercel AI SDK", [r"AI SDK(?! 7)", r"Vercel AI SDK", r"AI SDK 7"], "Kütüphane", "L05", "G03", ["akış", "ajan", "react"]),
    ("flutter-genui", "Flutter GenUI SDK", [r"Flutter GenUI", r"GenUI SDK", r"flutter/genui"], "Kütüphane", "L05", "G03", ["renderer", "mobil"]),
    ("httpagent", "AG-UI HttpAgent", [r"HttpAgent"], "Bileşen", "L05", "G03", ["istemci", "olay", "akış"]),
    # --- G04 Akış & taşıma
    ("sse", "Server-Sent Events", [r"\bSSE\b", r"Server-Sent Events"], "Standart", "L08", "G04", ["akış", "yeniden-bağlanma"]),
    ("eventsource", "EventSource", [r"EventSource"], "Tarayıcı API", "L08", "G04", ["akış", "tarayıcı"]),
    ("fetch-event-source", "fetch-event-source", [r"fetch-event-source"], "Kütüphane", "L08", "G04", ["akış", "yetkilendirme"]),
    ("websocket", "WebSocket", [r"WebSocket"], "Standart", "L08", "G04", ["çift-yönlü", "akış"]),
    ("http2", "HTTP/2", [r"HTTP/2", r"RFC 9113"], "Standart", "L08", "G04", ["taşıma", "vekil"]),
    ("last-event-id", "Last-Event-ID", [r"Last-Event-ID"], "Standart", "L08", "G04", ["yeniden-bağlanma", "yeniden-oynatma"]),
    ("abortcontroller", "AbortController", [r"AbortController"], "Tarayıcı API", "L08", "G04", ["iptal"]),
    ("jsonl", "JSONL", [r"\bJSONL\b", r"JSON Lines"], "Format/Şema", "L08", "G04", ["akış", "satır"]),
    ("json-patch", "JSON Patch (RFC 6902)", [r"JSON Patch", r"RFC 6902"], "Standart", "L08", "G04", ["yama", "akış"]),
    ("specstream", "SpecStream", [r"SpecStream"], "Format/Şema", "L08", "G04", ["akış", "yama", "tarif"]),
    # --- G05 Durum & veri
    ("xstate", "XState", [r"XState", r"Stately"], "Kütüphane", "L07", "G05", ["durum-makinesi", "yaşam-döngüsü"]),
    ("tanstack-query", "TanStack Query", [r"TanStack Query", r"React Query"], "Kütüphane", "L07", "G05", ["önbellek", "sunucu-durumu"]),
    ("tanstack-router", "TanStack Router", [r"TanStack Router"], "Kütüphane", "L07", "G05", ["yönlendirme", "url-durumu"]),
    ("tanstack-virtual", "TanStack Virtual", [r"TanStack Virtual", r"@tanstack/react-virtual"], "Kütüphane", "L07", "G05", ["sanallaştırma", "performans"]),
    ("react-concurrent", "React eşzamanlı API'leri", [r"useDeferredValue", r"startTransition", r"useTransition", r"flushSync"], "Tarayıcı API", "L07", "G05", ["öncelik", "performans", "react"]),
    ("react-suspense", "React Suspense", [r"Suspense"], "Bileşen", "L07", "G05", ["yükleme", "react"]),
    ("react-activity", "React Activity", [r"<Activity", r"\bActivity\b(?= (?:bileşen|API|component))"], "Bileşen", "L07", "G05", ["durum-koruma", "react"]),
    ("indexeddb", "IndexedDB", [r"IndexedDB"], "Tarayıcı API", "L07", "G05", ["kalıcılık", "çevrimdışı"]),
    ("service-worker", "Service Worker", [r"Service Worker"], "Tarayıcı API", "L07", "G05", ["çevrimdışı", "arka-plan"]),
    # --- G06 Dosya
    ("react-dropzone", "react-dropzone", [r"react-dropzone"], "Kütüphane", "L09", "G06", ["dosya-seçimi", "sürükle-bırak"]),
    ("uppy", "Uppy", [r"Uppy"], "Kütüphane", "L09", "G06", ["yükleme", "sürdürme", "çoklu-dosya"]),
    ("tus", "Tus", [r"\bTus\b", r"tus-js-client", r"Upload-Offset", r"tus\.io"], "Protokol", "L09", "G06", ["sürdürme", "yükleme"]),
    ("filepond", "FilePond", [r"FilePond"], "Kütüphane", "L09", "G06", ["yükleme", "önizleme"]),
    # --- G07 Hareket
    ("motion", "Motion", [r"(?<![-\w])Motion(?![-\w])(?! (?:for|One))", r"Framer Motion", r"AnimatePresence", r"motion\.dev"], "Kütüphane", "L04", "G07", ["animasyon", "yerleşim", "react"]),
    ("gsap", "GSAP", [r"GSAP(?! Flip)"], "Kütüphane", "L04", "G07", ["animasyon", "zaman-çizelgesi"]),
    ("gsap-flip", "GSAP Flip", [r"GSAP Flip", r"\bFlip\b"], "Kütüphane", "L04", "G07", ["yerleşim", "animasyon"]),
    ("animejs", "Anime.js", [r"Anime\.js", r"animejs"], "Kütüphane", "L04", "G07", ["animasyon"]),
    ("autoanimate", "AutoAnimate", [r"AutoAnimate"], "Kütüphane", "L04", "G07", ["liste", "animasyon", "sıfır-yapılandırma"]),
    ("rive", "Rive", [r"\bRive\b"], "Platform/Servis", "L04", "G07", ["varlık-animasyonu", "durum-makinesi"]),
    ("dotlottie", "dotLottie", [r"dotLottie", r"\bLottie\b", r"LottieFiles"], "Format/Şema", "L04", "G07", ["varlık-animasyonu"]),
    ("numberflow", "NumberFlow", [r"NumberFlow", r"number-flow"], "Kütüphane", "L04", "G07", ["sayı-geçişi", "intl"]),
    ("view-transitions", "View Transitions API", [r"View Transitions?(?: API)?", r"startViewTransition", r"cross-document"], "Tarayıcı API", "L04", "G07", ["geçiş", "tarayıcı", "sayfa"]),
    ("react-viewtransition", "React ViewTransition", [r"<ViewTransition", r"React ViewTransition", r"(?<!\w)ViewTransition(?!\w)"], "Bileşen", "L04", "G07", ["geçiş", "react"]),
    ("starting-style", "@starting-style", [r"@starting-style"], "Standart", "L04", "G07", ["css", "giriş-animasyonu"]),
    ("interpolate-size", "interpolate-size", [r"interpolate-size", r"calc-size"], "Standart", "L04", "G07", ["css", "boyut-animasyonu"]),
    ("waapi", "Web Animations API", [r"Web Animations API", r"\bWAAPI\b"], "Tarayıcı API", "L04", "G07", ["animasyon", "tarayıcı"]),
    ("reduced-motion", "prefers-reduced-motion", [r"prefers-reduced-motion", r"[Rr]educed[ -][Mm]otion", r"azaltılmış hareket"], "Standart", "L04", "G07", ["erişilebilirlik", "hareket-tercihi"]),
    # --- G08 AI etkileşim bileşenleri
    ("ai-elements", "AI Elements", [r"AI Elements"], "Kütüphane", "L03", "G08", ["ai-bileşeni", "onay", "shadcn"]),
    ("assistant-ui", "assistant-ui", [r"assistant-ui"], "Kütüphane", "L03", "G08", ["ai-bileşeni", "sohbet"]),
    ("ant-design-x", "Ant Design X", [r"Ant Design X", r"@ant-design/x", r"x\.ant\.design"], "Kütüphane", "L03", "G08", ["ai-bileşeni", "sohbet"]),
    ("thoughtchain", "ThoughtChain", [r"ThoughtChain"], "Bileşen", "L03", "G08", ["ai-bileşeni", "düşünce-zinciri"]),
    ("streamdown", "Streamdown", [r"Streamdown"], "Kütüphane", "L03", "G08", ["markdown", "akış"]),
    ("animate-ui", "Animate UI", [r"Animate UI", r"animate-ui"], "Kütüphane", "L03", "G08", ["hareketli-bileşen", "shadcn"]),
    ("magic-ui", "Magic UI", [r"Magic UI", r"magicui"], "Kütüphane", "L03", "G08", ["hareketli-bileşen", "açılış-sayfası"]),
    # --- G09 Görselleştirme
    ("echarts", "Apache ECharts", [r"ECharts"], "Kütüphane", "L10", "G09", ["grafik", "canvas"]),
    ("vega-lite", "Vega-Lite", [r"Vega-Lite", r"Vega-Embed", r"vega-embed"], "Format/Şema", "L10", "G09", ["grafik", "grafik-dilbilgisi", "bildirimsel"]),
    ("vega", "Vega", [r"\bVega\b(?!-)"], "Kütüphane", "L10", "G09", ["grafik", "ifade-dili"]),
    ("recharts", "Recharts", [r"Recharts"], "Kütüphane", "L10", "G09", ["grafik", "react"]),
    # --- G10 Güvenlik
    ("owasp-llm", "OWASP LLM Top 10", [r"OWASP", r"LLM0[1-9]", r"LLM10"], "Rehber", "L12", "G10", ["tehdit-modeli", "enjeksiyon"]),
    ("csp", "Content Security Policy", [r"\bCSP\b", r"Content Security Policy"], "Standart", "L12", "G10", ["izolasyon", "xss"]),
    ("iframe-sandbox", "iframe sandbox", [r"iframe sandbox", r"sandbox(?:ed)? iframe", r"\bsandbox\b"], "Standart", "L12", "G10", ["izolasyon"]),
    ("trusted-types", "Trusted Types", [r"Trusted Types"], "Tarayıcı API", "L12", "G10", ["xss", "tarayıcı"]),
    ("dompurify", "DOMPurify", [r"DOMPurify"], "Kütüphane", "L12", "G10", ["temizleme", "xss"]),
    # --- G11 Kapsayıcılık & token
    ("wcag", "WCAG 2.2", [r"WCAG"], "Standart", "L02", "G11", ["erişilebilirlik"]),
    ("wai-aria", "WAI-ARIA", [r"WAI-ARIA", r"\bARIA\b", r"aria-live"], "Standart", "L02", "G11", ["erişilebilirlik", "ekran-okuyucu"]),
    ("intl", "Intl API", [r"\bIntl\b"], "Tarayıcı API", "L02", "G11", ["yerelleştirme", "sayı-biçimi"]),
    ("resizeobserver", "ResizeObserver", [r"ResizeObserver"], "Tarayıcı API", "L02", "G11", ["yerleşim", "kapsayıcı"]),
    ("container-queries", "CSS Container Queries", [r"[Cc]ontainer [Qq]ueries", r"[Cc]ontainer [Qq]uery", r"@container"], "Standart", "L02", "G11", ["yerleşim", "kapsayıcı"]),
    ("design-tokens", "Design Tokens (DTCG)", [r"Design Tokens", r"\bDTCG\b", r"designtokens\.org"], "Standart", "L02", "G11", ["token", "marka"]),
    ("style-dictionary", "Style Dictionary", [r"Style Dictionary"], "Kütüphane", "L02", "G11", ["token", "derleme"]),
    ("figma", "Figma", [r"Figma"], "Platform/Servis", "L02", "G11", ["tasarım", "token"]),
    ("axe", "axe-core", [r"axe-core", r"@axe-core/playwright", r"\baxe\b", r"Deque"], "Test Aracı", "L11", "G11", ["erişilebilirlik", "test"]),
    # --- G12 Kalite
    ("playwright", "Playwright", [r"Playwright"], "Test Aracı", "L11", "G12", ["e2e", "test"]),
    ("vitest", "Vitest", [r"Vitest"], "Test Aracı", "L11", "G12", ["birim-test"]),
    ("msw", "MSW", [r"\bMSW\b", r"mswjs"], "Test Aracı", "L11", "G12", ["ağ-taklidi", "test"]),
    ("storybook", "Storybook", [r"Storybook"], "Test Aracı", "L11", "G12", ["bileşen-kataloğu", "görsel-test"]),
    ("testing-library", "Testing Library", [r"Testing Library"], "Test Aracı", "L11", "G12", ["birim-test", "erişilebilirlik"]),
    ("opentelemetry", "OpenTelemetry", [r"OpenTelemetry", r"semantic-conventions-genai"], "Standart", "L11", "G12", ["izleme", "iz-kimliği"]),
    ("inp", "INP", [r"\bINP\b", r"Interaction to Next Paint"], "Metrik", "L11", "G12", ["performans", "etkileşim"]),
    ("can-i-use", "Can I Use", [r"Can I Use", r"caniuse"], "Platform/Servis", "L11", "G12", ["uyumluluk"]),
    ("baseline", "Web Platform Baseline", [r"\bBaseline\b"], "Standart", "L11", "G12", ["uyumluluk"]),
    ("bcd", "MDN BCD", [r"\bBCD\b", r"browser-compat-data"], "Format/Şema", "L11", "G12", ["uyumluluk"]),
    ("mdn", "MDN Web Docs", [r"\bMDN\b"], "Rehber", "L11", "G12", ["belge", "uyumluluk"]),
    # --- S1 Kanıt tabanı
    ("generative-interfaces", "Generative Interfaces (arXiv 2508.19227)", [r"Generative Interfaces", r"2508\.19227", r"ConvUI"], "Araştırma", "L01", "S1", ["kullanıcı-tercihi", "genui"]),
    ("google-genui", "Google Research Generative UI", [r"Google Research", r"Google GenUI"], "Araştırma", "L01", "S1", ["genui", "kullanıcı-tercihi"]),
    ("design-theater", "Design Theater (arXiv 2607.22928)", [r"Design Theater", r"2607\.22928"], "Araştırma", "L01", "S1", ["tasarım-gerekçesi", "genui"]),
    ("nngroup", "Nielsen Norman Group", [r"NN/g", r"Nielsen Norman", r"nngroup"], "Rehber", "L01", "S1", ["bekleme", "kullanılabilirlik"]),
    ("gajos-2008", "Gajos 2008 — Öngörülebilirlik", [r"Gajos"], "Araştırma", "L01", "S1", ["uyarlanabilir-arayüz"]),
    ("viget-2017", "Viget 2017 — İskelet ekran deneyi", [r"Viget"], "Araştırma", "L01", "S1", ["bekleme", "iskelet"]),
    ("mejtoft-2018", "Mejtoft 2018 — İskelet ekran", [r"Mejtoft"], "Araştırma", "L01", "S1", ["bekleme", "iskelet"]),
    ("chung-2018", "Chung 2018 — İskelet ekran", [r"Chung"], "Araştırma", "L01", "S1", ["bekleme", "iskelet"]),
    ("counting-the-wait", "Counting the Wait (Tan–Nov, CHI 2026)", [r"Tan–Nov", r"Tan ve Nov", r"Counting the Wait", r"2602\.04138"], "Araştırma", "L01", "S1", ["bekleme", "ilerleme"]),
    ("carbon", "Carbon Design System", [r"Carbon"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi", "kurumsal"]),
    ("fluent", "Fluent 2", [r"Fluent"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("spectrum", "Adobe Spectrum", [r"React Spectrum", r"\bSpectrum\b"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi", "erişilebilirlik"]),
    ("atlassian-ds", "Atlassian Design System", [r"Atlassian"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("kolibri", "Kolibri Design System", [r"Kolibri"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("semrush-intergalactic", "Semrush Intergalactic", [r"Semrush", r"Intergalactic"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi", "iskelet"]),
    ("gitlab-pajamas", "GitLab Pajamas", [r"GitLab"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("ontario-ds", "Ontario Design System", [r"Ontario"], "Tasarım Sistemi", "L01", "S1", ["kamu", "bekleme-rehberi"]),
    ("nsw-ds", "NSW Design System", [r"\bNSW\b"], "Tasarım Sistemi", "L01", "S1", ["kamu", "bekleme-rehberi"]),
    ("backbase-ds", "Backbase Design System", [r"Backbase"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("oracle-apex", "Oracle APEX delayLinger", [r"Oracle", r"delayLinger"], "Rehber", "L01", "S1", ["bekleme-rehberi", "gecikme"]),
    ("vercel-guidelines", "Vercel Web Interface Guidelines", [r"Vercel Guidelines", r"vercel\.com/design"], "Rehber", "L01", "S1", ["bekleme-rehberi"]),
    ("acorn", "Firefox Acorn", [r"Acorn"], "Tasarım Sistemi", "L01", "S1", ["bekleme-rehberi"]),
    ("material", "Material Design", [r"Material Design", r"\bMaterial\b(?! UI)"], "Tasarım Sistemi", "L01", "S1", ["tasarım-dili"]),
    # --- S2 Ajan arka ucu & modeller
    ("pi", "Pi", [r"earendil-works/pi", r"pi-mono", r"@earendil-works/pi-agent-core"], "Framework", "L13", "S2", ["ajan", "typescript", "terminal", "araç-çağrısı", "çoklu-sağlayıcı"]),
    ("adk", "Google ADK", [r"\bADK\b"], "Framework", "L13", "S2", ["ajan", "a2ui"]),
    ("langgraph", "LangGraph", [r"LangGraph"], "Framework", "L13", "S2", ["ajan", "graf"]),
    ("langchain", "LangChain", [r"LangChain(?!\.)"], "Framework", "L13", "S2", ["ajan"]),
    ("mastra", "Mastra", [r"Mastra"], "Framework", "L13", "S2", ["ajan", "typescript"]),
    ("pydantic-ai", "Pydantic AI", [r"Pydantic AI", r"pydantic\.dev"], "Framework", "L13", "S2", ["ajan", "python"]),
    ("crewai", "CrewAI", [r"CrewAI"], "Framework", "L13", "S2", ["ajan", "çoklu-ajan"]),
    ("llamaindex", "LlamaIndex", [r"LlamaIndex"], "Framework", "L13", "S2", ["ajan", "rag"]),
    ("fastapi", "FastAPI", [r"FastAPI"], "Framework", "L13", "S2", ["sunucu", "python"]),
    ("temporal", "Temporal", [r"\bTemporal\b"], "Platform/Servis", "L13", "S2", ["iş-akışı", "dayanıklılık"]),
    ("nodejs", "Node.js", [r"Node\.js"], "Framework", "L13", "S2", ["sunucu"]),
    ("gemini", "Gemini", [r"Gemini"], "Model", "L14", "S2", ["model"]),
    ("claude", "Claude", [r"\bClaude\b"], "Model", "L14", "S2", ["model"]),
    ("gpt", "GPT / ChatGPT", [r"GPT-\d", r"ChatGPT", r"GPT-4o", r"OpenAI"], "Model", "L14", "S2", ["model"]),
    # --- S3 Platform & standartlar
    ("react", "React", [r"\bReact\b(?! (?:Aria|Spectrum|Query|Router|ViewTransition|SDK|DOM))", r"React 19(?:\.\d)?"], "Framework", "L15", "S3", ["ui-framework"]),
    ("vue", "Vue", [r"\bVue\b"], "Framework", "L15", "S3", ["ui-framework"]),
    ("angular", "Angular", [r"Angular"], "Framework", "L15", "S3", ["ui-framework"]),
    ("svelte", "Svelte", [r"Svelte"], "Framework", "L15", "S3", ["ui-framework"]),
    ("lit", "Lit", [r"\bLit\b"], "Framework", "L15", "S3", ["web-components"]),
    ("solid", "Solid", [r"\bSolid(?:JS)?\b"], "Framework", "L15", "S3", ["ui-framework"]),
    ("astro", "Astro", [r"\bAstro\b"], "Framework", "L15", "S3", ["adalar", "statik"]),
    ("nextjs", "Next.js", [r"Next\.js"], "Framework", "L15", "S3", ["react", "sunucu-bileşeni"]),
    ("vite", "Vite", [r"\bVite\b"], "Framework", "L15", "S3", ["derleme"]),
    ("lynx", "Lynx", [r"\bLynx\b", r"lynxjs"], "Framework", "L15", "S3", ["mobil", "çoklu-platform"]),
    ("flutter", "Flutter", [r"Flutter(?! GenUI)"], "Framework", "L15", "S3", ["mobil"]),
    ("web-components", "Web Components", [r"Web Components"], "Standart", "L15", "S3", ["web-components"]),
    ("vercel", "Vercel", [r"\bVercel\b(?! AI)(?! Guidelines)"], "Platform/Servis", "L15", "S3", ["barındırma"]),
    ("chrome", "Chrome / Chromium", [r"Chrome", r"Chromium"], "Tarayıcı", "L16", "S3", ["tarayıcı"]),
    ("safari", "Safari / WebKit", [r"Safari", r"WebKit"], "Tarayıcı", "L16", "S3", ["tarayıcı"]),
    ("firefox", "Firefox / Gecko", [r"Firefox", r"Gecko"], "Tarayıcı", "L16", "S3", ["tarayıcı"]),
    ("edge", "Microsoft Edge", [r"\bEdge \d", r"Microsoft Edge"], "Tarayıcı", "L16", "S3", ["tarayıcı"]),
    ("w3c", "W3C", [r"\bW3C\b"], "Kuruluş", "L16", "S3", ["standart-kuruluşu"]),
    ("whatwg", "WHATWG", [r"WHATWG", r"HTML Living Standard"], "Kuruluş", "L16", "S3", ["standart-kuruluşu"]),
    ("ietf", "IETF / RFC", [r"\bIETF\b", r"\bRFC \d{4}", r"rfc-editor"], "Kuruluş", "L16", "S3", ["standart-kuruluşu"]),
]

# Araştırma konuları (R01–R28) ve iddiaları eşlemek için anahtar kelimeler
TOPIC_KEYWORDS = {
    "R01": ["etkileşim modeli", "başarı ölçüt", "görev tamamlama", "sabit arayüz", "tercih", "Generative Interfaces", "kullanıcı işi"],
    "R02": ["kontrollü", "bildirimsel", "açık uçlu", "yetki", "declarative", "open-ended", "karar hakkı"],
    "R03": ["Animate UI", "Magic UI", "NumberFlow", "AI Elements", "Ant Design X", "hazır bileşen", "envanter", "ThoughtChain"],
    "R04": ["Mantine", "MUI", "Ant Design", "shadcn", "HeroUI", "React Aria", "Radix", "headless", "UI kit"],
    "R05": ["bekleme", "spinner", "skeleton", "iskelet", "ilerleme", "Viget", "Mejtoft", "Chung", "gecikme", "minimum görün"],
    "R06": ["Motion", "GSAP", "Anime.js", "AutoAnimate", "View Transition", "@starting-style", "interpolate-size", "Rive", "Lottie", "Web Animations"],
    "R07": ["dosya", "yükleme", "Uppy", "Tus", "FilePond", "react-dropzone", "upload", "Upload-Offset"],
    "R08": ["AG-UI", "A2UI", "protokol", "MCP", "A2A", "birlikte çalışabilir"],
    "R09": ["json-render", "CopilotKit", "Tambo", "OpenUI", "Thesys", "renderer", "framework"],
    "R10": ["katalog", "registry", "yetenek sözleşme", "bileşen tanım", "sürüm politikası"],
    "R11": ["kompozisyon", "temsil seç", "planlama", "bileşen seç"],
    "R12": ["kısmi JSON", "JSONL", "JSON Patch", "SpecStream", "RFC 6902", "akışlı tarif", "ayrıştırma", "partial"],
    "R13": ["XState", "yaşam döngüsü", "durum makinesi", "reducer", "RunFinished", "iptal", "zaman aşımı"],
    "R14": ["SSE", "EventSource", "WebSocket", "Last-Event-ID", "fetch-event-source", "yeniden bağlan", "HTTP/2", "vekil"],
    "R15": ["TanStack Query", "önbellek", "veri sözleşme", "tenant", "güncellik", "kaynak doğrul"],
    "R16": ["form", "odak", "süreklilik", "onay", "geri al", "idempot", "kullanıcı eylem"],
    "R17": ["kayıtlı görünüm", "snapshot", "live view", "URL", "TanStack Router", "paylaşım", "yeniden üret"],
    "R18": ["yerleşim", "Container Quer", "ResizeObserver", "320", "kapsayıcı", "layout"],
    "R19": ["ECharts", "Vega", "grafik", "chart", "eksen"],
    "R20": ["token", "DTCG", "Design Tokens", "Style Dictionary", "marka", "tema"],
    "R21": ["WCAG", "erişilebilir", "ARIA", "ekran okuyucu", "klavye", "RTL", "yerelleştir", "bilişsel", "prefers-reduced-motion"],
    "R22": ["INP", "performans", "useDeferredValue", "sanallaştır", "TanStack Virtual", "kaynak bütçe", "paket boyut"],
    "R23": ["güvenlik", "OWASP", "XSS", "CSP", "sandbox", "enjeksiyon", "LLM01", "LLM05", "Trusted Types", "izolasyon"],
    "R24": ["test", "Playwright", "Vitest", "MSW", "Storybook", "değerlendirme", "eval"],
    "R25": ["gözlemlen", "OpenTelemetry", "izleme", "log", "günlük", "teşhis", "trace"],
    "R26": ["maliyet", "bakım", "lisans", "bağımlılık", "MIT", "Apache", "ücretli", "Pro"],
    "R27": ["çoklu iş", "ortak", "paralel", "çoklu sekme", "uzun yaşayan", "çakışma"],
    "R28": ["prototip", "yol haritası", "aşamalı", "kabul ölçüt", "durdurma"],
}
